### ISSUE TITLE
Error while segmenting from Dicom using pretrained network in a local setting

### ISSUE THREAD

**Issue by cthepeni** [hnguyentt/mousechd-napari#1]
Are these files the ones you find useful for diagnosing the problem ?

[on_startup.odt](https://github.com/hnguyentt/mousechd-napari/files/13412751/on_startup.odt)
[diagnosis_error_local_dcm.odt](https://github.com/hnguyentt/mousechd-napari/files/13412752/diagnosis_error_local_dcm.odt)

Cedric

**Comment by hnguyentt** [comment]
Thanks! If you encounter a segmentation failure when running the plugin on your local machine, it could be due to insufficient GPU memory. We recommend having a GPU with a memory capacity of 10GB or above for optimal performance.

I document some common issues here: https://github.com/hnguyentt/mousechd-napari/blob/master/docs/issues.md
